### ISSUE TITLE
Problems with Win10 path

### ISSUE THREAD

**Issue by xDarKFeniXx** [faebeee/react-component-creator-plugin#8]
When choosing a custom template in win10, you need to manually change the path to the template `\` to `/`

**Comment by Erythros** [comment]
This solved my issue from #9 . Thank you!

@faebeee I think it would be helpful if you could add a quick _note_ to the readme file.

**Comment by faebeee** [comment]
This bug should be fixed with https://github.com/component-creator-plugin/react-component-creator-plugin/releases/tag/v0.6.0

The plugin has been submitted to JetBrains and is pending approval. From the release page, you can download the plugin and install it by hand. Let me know, if the bug is gone. 
I have no possibility to test it on a win 10 machine

**Comment by xDarKFeniXx** [comment]
it doesn't work now. I've used  \ and / in path and plugin create empty folder
and Webstorm get IDE Fatal Errors
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at java.base/java.util.Scanner.<init>(Scanner.java:566)
	at io.fabs.util.FileUtils.getContent(FileUtils.java:23)
	at io.fabs.util.TemplateRenderer.render(TemplateRenderer.java:15)
	at io.fabs.util.Creator.writeFiles(Creator.java:42)
	at io.fabs.util.Creator.create(Creator.java:29)
	at io.fabs.util.Creator.run(Creator.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
	at io.fabs.util.AbstractCreatorAction.actionPerformed(AbstractCreatorAction.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:288)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:519)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:541)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by faebeee** [comment]
@xDarKFeniXx  I'll look into it. Thanks for the stacktrace.

**Comment by mrjelveh** [comment]
I have this problem too,
@faebeee still not fixed?

**Comment by VincentChris** [comment]
I have this problem too

**Comment by faebeee** [comment]
I'm installing a VM with windows to debug it.
Currently there is no fix

**Comment by faebeee** [comment]
Anyone knows java? Might need some help to fix this...

**Comment by xDarKFeniXx** [comment]
sorry, I learning javascript now

**Comment by ayaka209** [comment]
still empty directory
```
2021-02-07 18:30:02,092 [1425580]   INFO - rowsers.BrowserLauncherAppless - Exit code 1 
2021-02-07 18:30:02,092 [1425580]   INFO - rowsers.BrowserLauncherAppless - ϵͳ�Ҳ����ļ� file:///C:\Users\welov\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57\jbr\bin\.\doc\CUSTOMIZE.md��
 
2021-02-07 18:30:07,656 [1431144]   WARN - rowsers.BrowserLauncherAppless - [file:///C:\Users\welov\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57\jbr\bin\#vue-single-file-component] 
java.io.IOException: Failed to open file:///C:%5CUsers%5Cwelov%5CAppData%5CLocal%5CJetBrains%5CToolbox%5Capps%5CIDEA-U%5Cch-0%5C203.7148.57%5Cjbr%5Cbin%5C#vue-single-file-component. Error message: No such file or directory。

	at java.desktop/sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:115)
	at java.desktop/sun.awt.windows.WDesktopPeer.browse(WDesktopPeer.java:101)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:526)
	at com.intellij.ide.browsers.BrowserLauncherAppless.openWithDefaultBrowser(BrowserLauncherAppless.kt:120)
	at com.intellij.ide.browsers.BrowserLauncherAppless.openOrBrowse(BrowserLauncherAppless.kt:103)
	at com.intellij.ide.browsers.BrowserLauncherAppless.openOrBrowse$default(BrowserLauncherAppless.kt:64)
	at com.intellij.ide.browsers.BrowserLauncherAppless.browse(BrowserLauncherAppless.kt:49)
	at com.intellij.ide.browsers.BrowserLauncherAppless.openOrBrowse(BrowserLauncherAppless.kt:97)
	at com.intellij.ide.browsers.BrowserLauncherAppless.browse(BrowserLauncherAppless.kt:148)
	at com.intellij.ide.BrowserUtil.browse(BrowserUtil.java:83)
	at com.intellij.ide.BrowserUtil.browse(BrowserUtil.java:79)
	at com.intellij.ui.BrowserHyperlinkListener.hyperlinkActivated(BrowserHyperlinkListener.java:14)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:11)
	at java.desktop/javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:345)
	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:899)
	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:695)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:55)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:514)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-02-07 18:30:10,675 [1434163]   INFO - rowsers.BrowserLauncherAppless - Exit code 1 
2021-02-07 18:30:10,675 [1434163]   INFO - rowsers.BrowserLauncherAppless - ϵͳ�Ҳ����ļ� file:///C:\Users\welov\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57\jbr\bin\#vue-single-file-component��
 
2021-02-07 18:31:20,928 [1504416]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - java.lang.Exception: null for file templates\component\{{componentName}}.vue 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at io.fabs.util.Creator.writeFiles(Creator.java:44) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at io.fabs.util.Creator.create(Creator.java:28) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at io.fabs.util.Creator.run(Creator.java:52) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at io.fabs.util.AbstractCreatorAction.actionPerformed(AbstractCreatorAction.java:52) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110) 
2021-02-07 18:31:34,775 [1518263]   INFO -                         STDERR - 	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:514) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Component.processEvent(Component.java:6417) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Container.processEvent(Container.java:2263) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) 
2021-02-07 18:31:34,776 [1518264]   INFO -                         STDERR - 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749) 
2021-02-07 18:31:34,777 [1518265]   INFO -                         STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
2021-02-07 18:31:34,778 [1518266]   INFO -                         STDERR - 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
2021-02-07 18:31:34,779 [1518267]   INFO -                         STDERR - Caused by: java.lang.NullPointerException 
2021-02-07 18:31:34,779 [1518267]   INFO -                         STDERR - 	... 54 more 
```
